"""changed_model_article

Revision ID: e1f33bea60a2
Revises: ec8c84c63dc6
Create Date: 2023-03-08 21:35:58.352315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f33bea60a2'
down_revision = 'ec8c84c63dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), server_default='', nullable=False))
        batch_op.add_column(sa.Column('body', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('dt_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('dt_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('dt_updated')
        batch_op.drop_column('dt_created')
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
